shader_root_dir: C:/Users/junbs/OneDrive/Documents/GitHub/see_with_you/include/shader
svo_file: C:/Users/junbs/OneDrive/Documents/ZED/HD1080_SN28007858_14-25-48.svo
tsdf: # volumetric meshing
  voxel_size: 0.015 # [m]
  trunc: 0.04 # [m]
  block_count: 1000
objects:
  active: true
  weight: C:/Users/junbs/OneDrive/Documents/GitHub/see_with_you/param/yolov4.weights
  cfg: C:/Users/junbs/OneDrive/Documents/GitHub/see_with_you/param/yolov4.cfg
  names: C:/Users/junbs/OneDrive/Documents/GitHub/see_with_you/param/coco.names
  confidence: 0.2